# Generated by Django 4.1.3 on 2023-02-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_duration',
            field=models.IntegerField(default=120, verbose_name='duration'),
        ),
    ]
